### PR TITLE
Check for both nil and zero length

### PR DESCRIPTION
**Pull request by jwhonce**
Signed-off-by: Jhon Honce <jhonce@redhat.com>

### CODE REVIEW

**Comment by jwhonce** [comment]
@TomSweeneyRedHat FYI

**Comment by TomSweeneyRedHat** [comment]
@giuseppe and @rhatdan PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM, tyvm @jwhonce

**Comment by giuseppe** [comment]
LGTM

**Comment by rhatdan** [comment]
Do we actually ship this package anywhere?

**Comment by TomSweeneyRedHat** [comment]
To answer @rhatdan, yes we still ship this with Docker.

**Comment by rhatdan** [comment]
So we package this up as docker-runc?

**Comment by TomSweeneyRedHat** [comment]
From what @control-d showed me, yes, we basically package it up as docker-runc.  He or @jnovy could explain it far better than I, but there's packaging code that makes it happen.

**Pull request merged**
