### PR TITLE
[4.8] cgroupv1 freezer: thaw to increase freeze chances

### PR DESCRIPTION
**Pull request by kolyshkin**
This backports https://github.com/opencontainers/runc/pull/2791 to rhaos-4.8 branch (i.e. on top of runc 1.0.0-rc93). In case we won't be upgrading to rc94 (once out) in 4.8, this may be of use.

This should fix https://bugzilla.redhat.com/show_bug.cgi?id=1903228

Original description follows

----

It appears that briefly thawing the cgroup while freezing
greatly increases its chances to freeze successfully.

The test case I used is doing runc exec in a look parallel with runc
pause/resume in another loop, and the failure to freeze rate reduced
from 40 to 0 per minute (tested inside a VM using a busybox container
running sleep 1h, doing about 1500 pause/resumes and 650 execs per
minute), with max retries being 150 (of 1000).

This is still a game of chances, so failures are possible.

Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>
(cherry picked from commit d1007b08a33ae63bb695fcb3244300c9bba2658a)
Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>

### CODE REVIEW

**Comment by haircommander** [comment]
huh, we have gh actions now, and they're also failing :)

**Comment by kolyshkin** [comment]
> huh, we have gh actions now, and they're also failing :)

Ah, this is because of rc1 which got removed. Fixed by  https://github.com/projectatomic/runc/pull/42

**Comment by kolyshkin** [comment]
rebased on top of merged #42 to make ci green

**Comment by haircommander** [comment]
LGTM, I'll merge with green CI

**Pull request merged**
