### PR TITLE
[4.8] libct/cg/fs/freezer: make sure to thaw on failure

### PR DESCRIPTION
**Pull request by saschagrunert**
Function (*FreezerGroup).Set has a few paths where in can return an
error. In any case, if an error is returned, we failed to freeze,
and we need to thaw to avoid leaving the cgroup in a stuck state.

Cherry-picked: fcd7fe85e1ea706fbdfb383824e9f390a53a34e9
Refers to: https://github.com/projectatomic/runc/pull/47

cc @kolyshkin @haircommander

### CODE REVIEW

**Comment by haircommander** [comment]
LGTM

**Comment by kolyshkin** [comment]
@saschagrunert can you also pick up https://github.com/opencontainers/runc/pull/2941?

**Comment by saschagrunert** [comment]
> @saschagrunert can you also pick up [opencontainers/runc#2941](https://github.com/opencontainers/runc/pull/2941)?

Isn't it already in: https://github.com/projectatomic/runc/pull/52 ?

**Comment by saschagrunert** [comment]
> @saschagrunert can you also pick up [opencontainers/runc#2941](https://github.com/opencontainers/runc/pull/2941)?

Done in https://github.com/projectatomic/runc/pull/53

**Review by kolyshkin — APPROVED** [review]
LGTM

**Comment by kolyshkin** [comment]
Close/reopen to re-kick CI

**Pull request merged**
