### PR TITLE
Remove systemd feature check

### PR DESCRIPTION
**Pull request by mrunalp**
@rhatdan @runcom PTAL

This should rid of the systemd error when it doesn't like scope with no pids. Tested working fine on RHEL 7.3 and Fedora. I will follow on this upstream as well. 

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
We are getting complaints from customers seeing entries in their log files by systemd complaining about this call.  I don't believe there are any systemd's around that do not support the feature, so we don't need to check any longer.

**Comment by slamp** [comment]
We have the same problem (Redhat 7.3, docker docker-1.12.6-11.el7.x86_64).
/var/log/message is flooded

**Comment by runcom** [comment]
Lgtm, @mrunal do we need this for 1.13.x and forward?

**Comment by runcom** [comment]
also, maybe we should propose this upstream right?

**Comment by mrunalp** [comment]
Let us carry this patch for now.

**Comment by runcom** [comment]
@mrunalp do we need this and #7 for the docker-1.13.1 branch as well?

**Comment by mrunalp** [comment]
Yes we do.

**Comment by runcom** [comment]
I'll port these fixes to 1.13.1 then..

**Comment by runcom** [comment]
alright, backported

**Pull request merged**
