### PR TITLE
BACKPORT: Fix race in exec

### PR DESCRIPTION
**Pull request by mrunalp**
Backport of upstream PR 1812

@rhatdan @runcom @lsm5 PTAL

We need to build a rpm for this PR and then get it tested before we release a new docker rpm.

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by lsm5** [comment]
@fkluknav could you please build a test rpm for this ?

**Comment by fkluknav** [comment]
docker rpms with this cri-o for rhel at https://fkluknav.fedorapeople.org/

**Comment by runcom** [comment]
has this been tested and can be merged?

**Pull request merged**
