### PR TITLE
Backport of copyup for tmpfs

### PR DESCRIPTION
**Pull request by mrunalp**
@rhatdan @runcom PTAL

### CODE REVIEW

**Comment by runcom** [comment]
LGTM we need it for docker-1.12 branch as well

(and side note, we need to setup a 1.13 branch to carry the delay IPC ns delayed join patch)

**Comment by rhatdan** [comment]
Can we default this to true?
We need
docker run -d --read-only --tmpfs /run httpd 
to work by default.

**Comment by rhatdan** [comment]
But this LGTM

**Comment by mrunalp** [comment]
We could default it in docker.

**Comment by mrunalp** [comment]
We can default it in docker.

**Pull request merged**
