### PR TITLE
Use uint64 for resources to keep consistency with runtime-spec

### PR DESCRIPTION
**Pull request by filbranden**
This is a backport of opencontainers/runc#1375 and it fixes https://github.com/kubernetes/kubernetes/issues/61474#issuecomment-383748728 but please note there were some follow ups to that commit in upstream runc, not sure if those should be considered here as well...

Signed-off-by: Qiang Huang <h.huangqiang@huawei.com>

(cherry-picked from commit 8430cc4f488f1925df01e517358c2a4cce8de176)
Signed-off-by: Filipe Brandenburger <filbranden@google.com>

### CODE REVIEW

**Comment by vfreex** [comment]
Because of this issue, OpenShift/Kubernetes nodes can't be run on latest Fedora.
This is definitely a high priority bug. I am surprised this issue doesn't get much attention.

**Comment by dustymabe** [comment]
FYI: related BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1584909#c4

**Comment by runcom** [comment]
@mrunalp PTAL

**Comment by filbranden** [comment]
So this was fixed with 18eb957e56a79e03fd43c37581200e3f4f392676 which reverts the backports.

I think you might want to consider adding back the changes around `StartTransientUnit`, since there seems to be a race condition there. That's opencontainers/runc#1772 and two or three other PRs that precede it. See opencontainers/runc#1683 for the first fix in the series, which discusses the race condition a bit...

This one is no longer relevant, so closing. Thanks!

**Comment by runcom** [comment]
> So this was fixed with 18eb957 which reverts the backports.
> 
> I think you might want to consider adding back the changes around StartTransientUnit, since there seems to be a race condition there. That's opencontainers/runc#1772 and two or three other PRs that precede it. See opencontainers/runc#1683 for the first fix in the series, which discusses the race condition a bit...
> 
> This one is no longer relevant, so closing. Thanks!

thanks for the pointer, do you have an ordered list of the fixes that must go in? I can't seem to follow every fix that went in :confused:

**Comment by runcom** [comment]
@filbranden ^^

**Comment by filbranden** [comment]
@runcom If you want to fix the race condition, then you need:

- opencontainers/runc#1683
- opencontainers/runc#1754
- opencontainers/runc#1772
- opencontainers/runc#1781

But see also [this comment](https://github.com/kubernetes/kubernetes/pull/61926#discussion_r181484929), since it seems the two first PRs were merged here (or in another branch) and later reverted. They introduced bugs that were later fixed by the last two PRs.

You should check with @sjenning, @mrunalp, @vikaschoudhary16 and @derekwaynecarr to see whether these PRs should be backported here or not.

This is about the race with systemd and libcontainer trying to mkdir the directories in the cgroup tree. That's all this patch set fixes.

Cheers,
Filipe

**Comment by runcom** [comment]
Thanks a lot!!!

**Comment by dustymabe** [comment]
> Because of this issue, OpenShift/Kubernetes nodes can't be run on latest Fedora.
> This is definitely a high priority bug. I am surprised this issue doesn't get much attention.

@vfreex - can I get you to test/karma https://bodhi.fedoraproject.org/updates/FEDORA-2018-c2e93d5623 ?

**Pull request closed without merging**
